 # Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.
#baseurl: "/dorian.gravier.github.io"


show_downloads: false

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
email                    : "dorian.gravier(at)gmail.com"
locale                   : "en-US"
title                    : "Personal Website"
title_separator          : "-"
name                     : &name "Dorian Gravier" # &name is a YAML anchor which can be *referenced later
github_name              : "DGrv"
subtitle                 : "Dorian Gravier"
# description              : &description "A flexible Jekyll theme for your blog or site with a minimalist aesthetic."
url                      : https://dorian.gravier.com
# baseurl                  : "/minimal-mistakes" # the subpath of your site, e.g. "/blog"
repository               : "DGrv/dorian.gravier.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : false # false (default), "disqus", "discourse", "facebook", "staticman_v2", "staticman", "utterances", "giscus", "custom"
  # disqus:
    # shortname            :
  # discourse:
    # server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  # facebook:
    # # https://developers.facebook.com/docs/plugins/comments
    # appid                :
    # num_posts            : # 5 (default)
    # colorscheme          : # "light" (default), "dark"
  # utterances:
    # theme                : # "github-light" (default), "github-dark"
    # issue_term           : # "pathname" (default)
  # giscus:
    # repo_id              : # Shown during giscus setup at https://giscus.app
    # category_name        : # Full text name of the category
    # category_id          : # Shown during giscus setup at https://giscus.app
    # discussion_term      : # "pathname" (default), "url", "title", "og:title"
    # reactions_enabled    : # '1' for enabled (default), '0' for disabled
    # theme                : # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
# reCaptcha:
  # siteKey                : # "6LdRBykTAAAAAFB46MnIu6ixuxwu9W1ihFF8G60Q"
  # secret                 : # "PznnZGu3P6eTHRPLORniSq+J61YEf+A9zmColXDM5icqF49gbunH51B8+h+i2IvewpuxtA9TFoK68TuhUp/X3YKmmqhXasegHYabY50fqF9nJh9npWNhvITdkQHeaOqnFXUIwxfiEeUt49Yoa2waRR7a5LdRAP3SVM8hz0KIBT4="

# atom_feed:
  # path                   : # blank (default) uses feed.xml

# search                   : true # true, false (default)
# search_full_content      : true # true, false (default)
# search_provider          : algolia # lunr (default), algolia
# algolia:
  # application_id         : QB6HVGBSBA # YOUR_APPLICATION_ID
  # index_name             : minimal_mistakes # YOUR_INDEX_NAME
  # search_only_api_key    : 9d5014e5bbc77372547bce778dfa5663 # YOUR_SEARCH_ONLY_API_KEY
  # powered_by             : true # true (default), false
  # files_to_exclude:
    # - _posts/2017-11-28-post-exclude-search.md

# # SEO Related
# google_site_verification : "UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y" # Replace this with your ID, or delete
# bing_site_verification   :
# naver_site_verification  :
# yandex_site_verification :
# baidu_site_verification  :

# # Social Sharing
# twitter:
  # username               : &twitter "mmistakes"
# facebook:
  # username               : &facebook "michaelrose"
  # app_id                 :
  # publisher              :
# og_image                 : "/assets/images/site-logo.png" # Open Graph/Twitter default site image
# # For specifying social profiles, used in _includes/seo.html
# # - https://developers.google.com/structured-data/customize/social-profiles
# social:
  # type                   : # Person or Organization (defaults to Person)
  # name                   : # If the user or organization name differs from the site's name
  # links: # An array of links to social media profiles
    # - "https://twitter.com/mmistakes"
    # - "https://www.facebook.com/michaelrose"











# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "UA-32529331-1" # Replace this with your ID, or delete
    anonymize_ip         : true


# Reading Files
include:
  - .htaccess
  - _pages
exclude: # otherwse way too slow https://stackoverflow.com/questions/26855552/jekyll-compiling-seems-way-too-slow
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
      
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      
      
      
# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/dori-head.jpg"
  bio              : "Just another *boring*, *autodidact*, *climber*, *biker*, *time traveler*, and *french dude*."
  location         : "Konstanz, DE"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dgrv"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/oyo_libro"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@oYoLibro"




# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false



# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# # Outputting
# permalink: /:categories/:title/
# # paginate: 5 # amount of posts to show
# # paginate_path: /page:num/


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache



# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
