theme: minima
repository: "DGrv/dorian.gravier.github.io"
github: [metadata]
title: Dorian Gravier Personal Website
email: dorian.gravier(at)gmail.com
github_name: DGrv
baseurl: "/dorian.gravier.github.io"
url: "https://dgrv.github.io"
highlighter: pygments
# plugins:
#  - jekyll-include-cache
#  - jekyll-sitemap
#  - jekyll-remote-theme
