theme: 
remote_theme: mmistakes/minimal-mistakes
repository: "DGrv/dorian.gravier.github.io"
github: [metadata]
title: Dorian Gravier Personal Website
email: dorian.gravier(at)gmail.com
github_name: DGrv
baseurl: "/dorian.gravier.github.io"
url: "https://dgrv.github.io"
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-remote-theme