// create file
var Bike = ['files/gpx/Bike/B_201511_mtb.gpx',
'files/gpx/Bike/B_2017_Stockach_DonauTalRadoflzell-Konstanz.gpx',
'files/gpx/Bike/B_201709_Bike_Travel.gpx',
'files/gpx/Bike/B_201808_Schwarzwald.gpx',
'files/gpx/Bike/B_201809_Bike_Switzerland.gpx',
'files/gpx/Bike/B_201812_LesForges.gpx',
'files/gpx/Bike/B_201904_Ruegen_insel_runde.gpx',
'files/gpx/Bike/B_201906_FrankenJura_0001.gpx',
'files/gpx/Bike/B_201906_FrankenJura_0002.gpx',
'files/gpx/Bike/B_201906_FrankenJura_0003.gpx',
'files/gpx/Bike/B_201906_FrankenJura_0004.gpx',
'files/gpx/Bike/B_201906_FrankenJura_0005.gpx',
'files/gpx/Bike/B_201906_FrankenJura_0006.gpx',
'files/gpx/Bike/B_201906_FrankenJura_0007.gpx',
'files/gpx/Bike/B_201906_FrankenJura_0008.gpx',
'files/gpx/Bike/B_201906_FrankenJura_0009.gpx',
'files/gpx/Bike/B_201906_FrankenJura_0010.gpx',
'files/gpx/Bike/B_201906_FrankenJura_0011.gpx',
'files/gpx/Bike/B_201906_FrankenJura_0012.gpx',
'files/gpx/Bike/B_201906_FrankenJura_0013.gpx',
'files/gpx/Bike/B_201906_FrankenJura_0014.gpx',
'files/gpx/Bike/B_20200424_Olima.gpx',
'files/gpx/Bike/B_20200426_Olima.gpx',
'files/gpx/Bike/B_20200428_Olima.gpx',
'files/gpx/Bike/B_20200501_Olima.gpx',
'files/gpx/Bike/B_20200503_Olima.gpx']

var Hike = ['files/gpx/Hike/2017_Grosser_Mythen.gpx',
'files/gpx/Hike/2017_KS_2TAllgauerHochalpen-NebelhornzuGrosserDaumen.gpx',
'files/gpx/Hike/2017_KS1T_Hinterstein-Rotspitze.gpx',
'files/gpx/Hike/2017_Luetispitze.gpx',
'files/gpx/Hike/2017_Nord_LechtalElbigenalp-Krotenkopf-Ubeleskarspitze-Hinterbornbach.gpx',
'files/gpx/Hike/201708_Druesberg.gpx',
'files/gpx/Hike/201711_Wgausflug.gpx',
'files/gpx/Hike/2018_W_HochYbrig_Druesberg.gpx',
'files/gpx/Hike/201804_Bockmattli.gpx',
'files/gpx/Hike/201804_Pfaender.gpx',
'files/gpx/Hike/201805_WG_Hike_0001.gpx',
'files/gpx/Hike/201805_WG_Hike_0002.gpx',
'files/gpx/Hike/201806_Zimba.gpx',
'files/gpx/Hike/201808_Feldberg.gpx',
'files/gpx/Hike/201809_Ottenhofen_imSchwarzwaldHiking.gpx',
'files/gpx/Hike/201810_Pizol.gpx',
'files/gpx/Hike/201811_Silberplatte_Klettern.gpx',
'files/gpx/Hike/201903_Saechsische_Schweiz.gpx_250.gpx',
'files/gpx/Hike/201910_Donautal.gpx',
'files/gpx/Hike/201910_Tajakante.gpx',
'files/gpx/Hike/brunnenhochflue-t4.gpx',
'files/gpx/Hike/chaeserrugg_vonwalenstadt.gpx',
'files/gpx/Hike/hohenschwangauwildsulzhuette-saeuling-saeulinghau.gpx',
'files/gpx/Hike/murgtal_murgseeturm.gpx',
'files/gpx/Hike/plattberg_upssitzeostreich.gpx',
'files/gpx/Hike/saentis_vonsudden.gpx',
'files/gpx/Hike/sarek_2016.gpx',
'files/gpx/Hike/um_herumdergimpel.gpx',
'files/gpx/Hike/via_dellebochette.gpx',
'files/gpx/Hike/W_2013_Ebenalp.gpx',
'files/gpx/Hike/W_2013_Marwees.gpx',
'files/gpx/Hike/W_2015_Rosteinpass.gpx',
'files/gpx/Hike/W_2015_Saxer-luecke.gpx',
'files/gpx/Hike/W_2016_Santis.gpx',
'files/gpx/Hike/W_2017_Alpstein.gpx']

var HikeProject = ['files/gpx/Hike/Project/AKD_project.gpx',
'files/gpx/Hike/Project/moe_saladinspitze_rotewand_.gpx',
'files/gpx/Hike/Project/moew-paiserspitze_.gpx']

var SchitourProject = ['files/gpx/Schitour/Project/P_ST_moe-st-2t-carschinahuette.gpx',
'files/gpx/Schitour/Project/P_ST_moe-st-2t-carschinahuette_2.gpx',
'files/gpx/Schitour/Project/P_ST_moe-st-2t-claridenhuette.gpx',
'files/gpx/Schitour/Project/P_ST_moe-st-2t-heilbronner_huette.gpx',
'files/gpx/Schitour/Project/P_ST_moe-st-hirschberg.gpx',
'files/gpx/Schitour/Project/P_ST_moe-st-mattjischhorn.gpx',
'files/gpx/Schitour/Project/P_ST_moe-st_alpilakopf.gpx',
'files/gpx/Schitour/Project/P_ST_moe-st_analperjoch.gpx',
'files/gpx/Schitour/Project/P_ST_moe-st_gafier.gpx',
'files/gpx/Schitour/Project/P_ST_moe-st_gampapingalpe.gpx',
'files/gpx/Schitour/Project/P_ST_moe-st_gerenspitze.gpx',
'files/gpx/Schitour/Project/P_ST_moe-st_windeggerspitze.gpx',
'files/gpx/Schitour/Project/P_ST_st-moematona.gpx',
'files/gpx/Schitour/Project/P_ST_st-moemoerzelspitze.gpx',
'files/gpx/Schitour/Project/P_ST_Vogelberg-Zapporthutte-SAC.gpx']

var Schitour = ['files/gpx/Schitour/ST_2016_biet_weglosen.gpx',
'files/gpx/Schitour/ST_2016_ober_kamorschitour.gpx',
'files/gpx/Schitour/ST_2017_Innerlatenrns.gpx',
'files/gpx/Schitour/ST_201711_LindauHutte.gpx',
'files/gpx/Schitour/ST_2018_Fullfirst.gpx',
'files/gpx/Schitour/ST_2018_Gross-Chaerpf.gpx',
'files/gpx/Schitour/ST_201901_Gamperdun.gpx',
'files/gpx/Schitour/ST_201901_Stockberg.gpx',
'files/gpx/Schitour/ST_201902_Schneeglocke.gpx',
'files/gpx/Schitour/ST_201903_Klostertaler-Egghorn.gpx',
'files/gpx/Schitour/ST_201903_Sonntagspitze.gpx',
'files/gpx/Schitour/ST_201911_Stotzigen_Firsten.gpx']

var SchneeSProject = ['files/gpx/SchneeS/Project/P_SW_Malans-Tschugga.gpx',
'files/gpx/SchneeS/Project/P_SW_Mattner_first.gpx',
'files/gpx/SchneeS/Project/P_SW_Nussen_innertal.gpx',
'files/gpx/SchneeS/Project/P_SW_Silberen.gpx',
'files/gpx/SchneeS/Project/P_SW_Wilhaus_1.gpx']

